name = "onegrape"
type = "webpack"
workers_dev = true
account_id = "47a8d28cdce754edf9966f30cf9e03e6"
zone_id = "e9d8f81be5c593d7e7e44570e8dbf311"
kv_namespaces = [
    { binding = "BUCKET", id = "7a702c6b0b5341d38fea90b498086878" }
]

[env.staging]
name = "drive-staging"
